port: 3000
bindIP: 0.0.0.0
logLevel: info
dataPath: ./data

db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: wikijsrocks
  db: wiki
  ssl: false

ssl:
  enabled: true
  port: 3443
  provider: custom
  format: pem
  key: /wiki/ssl/key.pem
  cert: /wiki/ssl/cert.pem

