name: ecoserv 

services:
  nginx:
    extends:
      file: ./proxy/docker-compose.yml
      service: nginx

  metadata-db:
    extends:
      file: ./metadata-db/docker-compose.yml
      service: db

  wiki:
    extends:
      file: ./wiki/docker-compose.yml
      service: wiki

  forgejo:
    extends:
      file: ./versionado/docker-compose.yml
      service: server

  uptime-kuma:
    extends:
      file: ./monitoreo/uptime-kuma/docker-compose.yml
      service: uptime-kuma

  netdata:
    extends:
      file: ./monitoreo/netdata/docker-compose.yml
      service: netdata

  adminer:
    extends:
      file: ./db-manager/docker-compose.yml
      service: adminer

networks:
  ecoserv-net:
    driver: bridge
    attachable: true # Let other services connect to this network
    external: false # It's created when for this services.
    name: ecoserv-net # custom name to avoid naming with project.
  
volumes:
  kuma-data:
  metadata-db:
  netdataconfig:
  netdatalib:
  netdatacache:

