services:
  server:
    image: codeberg.org/forgejo/forgejo:12
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000

      - DEFAULT_THEME=forgejo-light

      # Database config (PostgreSQL central)
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=metadata-db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo

    restart: always
    networks:
      - ecoserv-net
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    ports:
      - "222:22"   # SSH para git clone/push

    depends_on:
      - db

volumes:
  data:

# networks:
#   ecoserv-net:
#     external: true

