services:
  db:
    image: postgres:16
    container_name: metadata-db
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
      #- ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # add entry point to create tables for every needed service ?
    networks:
        - backend
  
volumes:
  metadata-db:
networks:
  backend:
    external: true
